### ISSUE TITLE
Analysis of SDK internals (make sure they are "Pythonic")

### ISSUE THREAD

**Issue by toddbaert** [open-feature/python-sdk#102]
As mentioned in https://github.com/open-feature/python-sdk/issues/101, some of the SDK internals aren't very python-idiomatic. We should create some tasks to refactor this.

Definition of done:

- [ ] Investigate all internal (non-public) artifacts/classes and evaluate for adherence to Python idioms
- [ ] Create individual issues with specific goals for each

**Comment by beeme1mr** [comment]
I believe this has been addressed in the recent v0.7 release. @federicobond could you please confirm?
