### ISSUE TITLE
Changes to support spec `v0.6.0` compliance

### ISSUE THREAD

**Issue by toddbaert** [open-feature/python-sdk#125]
:warning: 0.6.0 should probably be undertaken only after the existing [1.0-functional requirements](https://github.com/open-feature/python-sdk/issues?q=is%3Aissue+is%3Aopen+label%3A1.0-release) are complete.

## Implement specification v0.6.0 changes

See [changes since last release](https://github.com/open-feature/spec/compare/v0.5.2...v0.6.0).

Please note there's no need to complete all these tasks in a single PR (in fact, that's not recommended). Consider creating a new sub issue for each of the below requirements.

### Functional requirements:

- [x] implement flag metadata: https://github.com/open-feature/spec/commit/74c373e089ad77bf8cac84f3d93c00c945ff3a8a
#212
- [x] implement named client support
- [x] Implement Initialize/Shutdown on provider registration: https://github.com/open-feature/spec/commit/a4ffec3d4416b8ad6d12d1ebfa2faf81ad153f65
#213 
- [x] Implement events https://github.com/open-feature/spec/blob/main/specification/sections/05-events.md
  - [x] #131 (API level events)

### Non-functional requirements:

- [x] add relevant tests
- [x] add examples and documentation, see template README
- [x] update specification badge to `v0.6.0`: [![Specification](https://img.shields.io/static/v1?label=Specification&message=v0.6.0&color=yellow)](https://github.com/open-feature/spec/tree/v0.6.0)

### Keep in mind:

- backwards compatibility is _highly encouraged_
  - take every precaution to ensure existing code written by _application authors_ and existing providers implementations, do not break
- it's recommended these features are released together

**Comment by federicobond** [comment]
There are no more directly actionable items in this issue 🎉 , so we are ready to close and handle any follow-up tasks in separate issues.
