### ISSUE TITLE
Implement API-Level Events

### ISSUE THREAD

**Issue by jamescarr** [open-feature/python-sdk#131]
There are no signals for various events that happen

This is optional as per the [spec](https://openfeature.dev/specification/sections/events) but useful for integrators.

Definition of done:

 * [ ] Event Handlers are registered via the global API
 * [ ] Events are emitted internally when they occur
 * [ ] associated tests

**Comment by toddbaert** [comment]
There's nothing wrong with implementing the API-level events in isolation - but I would caution that doing so (separately from client events) _could_ increase the chances that we have breaking changes in the client events implementation.

We should keep that in mind when we undertake this.
