### ISSUE TITLE
Use hatch for packaging and dependency management

### ISSUE THREAD

**Issue by thomaspoignant** [open-feature/python-sdk#133]
Poetry helps a lot for packaging and dependency management, it would be great to use it instead of pip.

**Comment by clesleycode** [comment]
Hi @thomaspoignant ! I'm looking for my first ticket to work on - can I take this one up?

**Comment by thomaspoignant** [comment]
Hey @clesleycode, this ticket is actually assigned to @jamescarr so it is maybe worth to check with him if he work ok it or not.

**Comment by federicobond** [comment]
Could you elaborate on the benefits of switching to poetry here? I am worried that it can introduce friction for new contributors.

**Comment by thomaspoignant** [comment]
> Could you elaborate on the benefits of switching to poetry here? I am worried that it can introduce friction for new contributors.

I've open this issue based on the discussion we had on slack https://cloud-native.slack.com/archives/C0344AANLA1/p1685730237454139

**Comment by federicobond** [comment]
Got it, thank you for the heads up. Looks like the main argument for introducing Poetry is better support for a monorepo approach to publishing multiple packages. We don't yet publish multiple packages from this repo, but it will probably be very useful for the python-sdk-contrib one and it's good to standardize in a single toolset for the project.

**Comment by gruebel** [comment]
@federicobond should we actually change this to migrate to `hatch` like in the `contrib` project to have identical tooling?

**Comment by federicobond** [comment]
I think it makes sense to try hatch for the SDK too.
