### ISSUE TITLE
FlagType enum definition causes problems with mypy

### ISSUE THREAD

**Issue by federicobond** [open-feature/python-sdk#135]
Running `mypy` on the sdk codebase I found several errors. One of them stood out:

```
open_feature/open_feature_client.py:202: error: Argument 1 to "evaluate_flag_details" of "OpenFeatureClient" has incompatible type "<typing special form>"; expected "FlagType"  [arg-type]
```

This corresponds to the following call:

https://github.com/open-feature/python-sdk/blob/d31b531ae8e4c9e52ac723a3574e85928479bb1a/open_feature/open_feature_client.py#L204-L210

It appears that mypy has problems recognizing the value of `FlagType.OBJECT` as a member of `FlagType`.

```python
class FlagType(Enum):
    BOOLEAN = bool
    STRING = str
    OBJECT = typing.Union[dict, list]
    FLOAT = float
    INTEGER = int
```

As we can see, `OBJECT` is the only value that is not a standard type class.

Using types as enum values like this is not very common and has the potential to cause issues with other tools too. Moving to standard `str` or `int` enum values may avoid such problems. If there is consensus in this I can open a pull request with the necessary changes.

**Comment by toddbaert** [comment]
I believe we need to support both dict and list, for objects, especially after [this change](https://github.com/open-feature/python-sdk/pull/134). Isn't that was this Union conveys?
If there's a typesafe way to do that besides the Union, that seems fine. I'm not sure I understand what solution you're proposing. :sweat_smile:

**Comment by federicobond** [comment]
What I am proposing is to decouple the FlagType enum values from the types they are supposed to check, and just have standard strings for the enum.

The FlagType could be defined as:

```python
class FlagType(Enum):
    BOOLEAN = 'BOOLEAN'
    STRING = 'STRING'
    OBJECT = 'OBJECT'
    FLOAT = 'FLOAT'
    INTEGER = 'INTEGER'
```

And the `isinstance(resolution.value, flag_type.value)` check would be replaced with a call to a function like this:

```python
def typecheck_flag_value(value, flag_type):
    type_map = {
        FlagType.BOOLEAN: bool,
        FlagType.STRING: str,
        FlagType.OBJECT: typing.Union[dict, list],
        FlagType.FLOAT: float,
        FlagType.INTEGER: int,
    }
    _type = type_map.get(flag_type)
    if not _type:
        raise GeneralError(error_message="Unknown flag type")
    if not isinstance(value, _type):
        raise TypeMismatchError(f"Expected type {_type} but got {type(value)}")

**Comment by Kavindu-Dodan** [comment]
@federicobond  thank you. I think I understand your proposal and I do not have any objection on this. However, I would really like opinion of Python experts :)

**Comment by federicobond** [comment]
I opened a pull request with my proposed change so we can have a more concrete artifact to comment/discuss on.

**Comment by federicobond** [comment]
Closed with https://github.com/open-feature/python-sdk/pull/137
