### ISSUE TITLE
Remove pypi token once the trusted publisher flow has been tested

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/python-sdk#231]
I've updated our account to accept this repo as a [trusted publisher](https://docs.pypi.org/trusted-publishers/adding-a-publisher/). This should allow us to remove the auth token we currently pass to the GitHub publishing action. Once we verify that it's working, the existing token should be removed.

**Comment by gruebel** [comment]
hey @beeme1mr just wanted to double check on what you exactly configured in `pypi`? Something like this

Repository: open-feature/python-sdk
Workflow: release.yml
Environment name: release

especially the last one would be great, if you can set it, then we can further tighten the publishing flow. And please also create such an environment in this project 😄

**Comment by beeme1mr** [comment]
I was missing the environment but I just added it.
