### ISSUE TITLE
Wording - Should we call objects dictionaries?

### ISSUE THREAD

**Issue by dlopes7** [open-feature/python-sdk#24]
It is not common to call dictionaries in python "objects", are we trying to use the same wording for all languages? I see that spec defines `Structure` so in my opinion `Dictionaries` would be more appealing to python developers

**Comment by beeme1mr** [comment]
The term `Structure` was chosen in the spec so that each SDK could choose the term that best fits the technology.

FYI, @toddbaert

**Comment by toddbaert** [comment]
Agreed! The Python SDK should use whatever language is most idiomatic to describe the relevant "structured data". See the definition in the spec here: https://github.com/open-feature/spec/blob/main/specification/types.md#structure.

So I'll leave it up to people with more Python chops than me! :sweat_smile:

**Comment by tcarrio** [comment]
As both @beeme1mr and @toddbaert have mentioned, this is up to each language to implement it as it makes sense.

> ## Structures
>
> Structured data, presented however is idiomatic in the implementation language
> [[Reference](https://docs.openfeature.dev/docs/specification/types#structure)]

I think the verbiage here should depend on what is actually being used, and in cases of context it appears that it's powered by dictionaries. Hook context is an object. It's also possible to allow for **either** to be provided, Python is dynamically typed and you can explicitly transform dictionaries into objects as one option.

Generally speaking, dictionaries makes sense to me, as long as that's actually what you're expecting to work with in the SDK (Wouldn't want any `TypeError`s trying to do `result['property']` on an object).

**Comment by thomaspoignant** [comment]
As mentioned in this [thread](https://cloud-native.slack.com/archives/C0344AANLA1/p1671207937612679), in other SDKs the `get_object_details` can return both array and object, I will expect this function to be able to return an `Union[dict, list]`.

So with that in mind object seems to be the right naming.

**Comment by federicobond** [comment]
Closing this issue as there appears to be a consensus on keeping the term object when referring to both arrays and dictionaries.
