### ISSUE TITLE
FlagResolutionDetails reason field should accept any string

### ISSUE THREAD

**Issue by keelerm84** [open-feature/python-sdk#262]
The [specification for resolution details](https://github.com/open-feature/spec/blob/main/specification/types.md#resolution-details) states that the reason field should be an optional string. There are some pre-defined reason values (reflected in the `Reason` enum), but a provider should be free to provide an arbitrary reason.

I believe the `FlagResolutionDetails.reason` field should be updated to store an `Optional[str]` instead of the current `Optional[Reason]`.

Happy to work on the PR if this seems acceptable.

See the [related issue on the SDK spec](https://github.com/open-feature/spec/issues/236).

**Comment by beeme1mr** [comment]
This relates to this issue recently opened in the spec.
https://github.com/open-feature/spec/issues/236

**Comment by gruebel** [comment]
Sounds reasonable, but I would prefer to change it to `Optional[Union[str, Reason]]` if possible. Then you indicate the user about an existing set of reasons, but still you can choose to add your own.

**Comment by gruebel** [comment]
My thinking was more about discoverability, because if it is set to `str`, then you wouldn't know about the predefined reasons and worst write your own.

If this will be adjusted, then we should also change the typing for `FlagEvaluationDetails`.

**Comment by beeme1mr** [comment]
> My thinking was more about discoverability, because if it is set to `str`, then you wouldn't know about the predefined reasons and worst write your own.

That's basically what we do in the JS SDK. You can see an example [here](https://github.com/open-feature/js-sdk/blob/main/packages/shared/src/evaluation/evaluation.ts#L17).
