### ISSUE TITLE
Create Provider Specific Evaluation Details Object

### ISSUE THREAD

**Issue by rgrassian-split** [open-feature/python-sdk#33]
Currently the Provider is expected to return a `FlagEvaluationDetails` object, the same that the client does. However it would probably be better to return a specific `ProviderEvaluationDetails` object instead so that the flag name does not need to be added and if one changes the other does not have to as well. We do this for the other sdks as well so this would make this sdk similar to them

**Comment by tcarrio** [comment]
Hey @rgrassian-split, are you referring to a separation of the [Evaluation Details](https://docs.openfeature.dev/docs/specification/types#evaluation-details) and the [Resolution Details](https://docs.openfeature.dev/docs/specification/types#resolution-details)? As far as I know that's how it is separated, the Resolution Details being the value returned by the provider, and the Evaluation Details being returned by the OpenFeature client.

**Comment by toddbaert** [comment]
Right! closed in favor of: https://github.com/open-feature/python-sdk/issues/97
