### ISSUE TITLE
Create end-to-end test suite

### ISSUE THREAD

**Issue by toddbaert** [open-feature/python-sdk#99]
Leverage the [test-harness](https://github.com/open-feature/test-harness) and [evaluation.feature](https://github.com/open-feature/test-harness/blob/main/features/evaluation.feature) gherkin suite to create a set of integration tests for the Python SDK. See equivalent examples in [Java](https://github.com/open-feature/java-sdk/tree/main/src/test/java/dev/openfeature/sdk/e2e) and [JS](https://github.com/open-feature/js-sdk/tree/main/packages/server/e2e). Though we should call these "end-to-end" not integration tests, since that's what they are.

The suite should start the test harness container and run it in CI (again, see references in [Java](https://github.com/open-feature/java-sdk/blob/main/.github/workflows/pullrequest.yml) and [JS](https://github.com/open-feature/js-sdk/blob/main/.github/workflows/pr-checks.yaml)).

NOTE: we'll need the [python flagd provider](https://github.com/open-feature/python-sdk-contrib/pull/3) first, but work can begin now with this partial version.

Definition of done:

- [ ] gherkin test suite complete and runs on CI
- [ ] updates to documentation (CONTRIBUTING.md)

**Comment by jamescarr** [comment]
@toddbaert the Java and JS links are 404 now... where do these currently live?

**Comment by jamescarr** [comment]
Took a quick look at the projects that implement this. 

### Java
* [Maven Task](https://github.com/open-feature/java-sdk/blob/b8b927e/pom.xml#L516-L569)
* [Step Definitions](https://github.com/open-feature/java-sdk/blob/b8b927ef4a418c32effb9fbc644667ec48a4ce7e/src/test/java/dev/openfeature/sdk/e2e/StepDefinitions.java)
* [Runner](https://github.com/open-feature/java-sdk/blob/b8b927ef4a418c32effb9fbc644667ec48a4ce7e/src/test/java/dev/openfeature/sdk/e2e/RunCucumberTest.java)

### Javascript
* [Jest Targets](https://github.com/open-feature/js-sdk/blob/5d55ea1/jest.config.ts#L130-L147)
* [Step Definitions](https://github.com/open-feature/js-sdk/tree/main/packages/server/e2e/step-definitions)
* [Runner](https://github.com/open-feature/js-sdk/blob/main/package.json#L8)

## Python Implementation
To implement this in python, we will need:

* [ ] Add test-harness as a submodule
* [ ]  Makefile target that copies the test-harness tests for running
* [ ] Add [gherkin-python](https://github.com/cucumber/gherkin-python) dev dependency
* [ ] Step definitions for cucumber tests
* [ ] Run e2e tests as part of Makefile via `make e2e`.

While the `python-sdk-contrib` flagd provider needs to be merged for this to work "for real," we can get the mechanics in place and it should work with the `NoOpProvider` for now.

Thoughts?

**Comment by toddbaert** [comment]
> @toddbaert the Java and JS links are 404 now... where do these currently live?

@jamescarr sorry about that. Those links are updated (we renamed the dirs and suites "e2e" from "integration", since e2e is a more accurate description).

> * [ ]  Add test-harness as a submodule
> * [ ]   Makefile target that copies the test-harness tests for running
> * [ ]  Add [gherkin-python](https://github.com/cucumber/gherkin-python) dev dependency
> * [ ]  Step definitions for cucumber tests
> * [ ]  Run e2e tests as part of Makefile via `make e2e`.
> 
> While the `python-sdk-contrib` flagd provider needs to be merged for this to work "for real," we can get the mechanics in place and it should work with the `NoOpProvider` for now.
> 
> Thoughts?

This sounds perfect to me. Simply getting the test suite (cucumber, etc), CI working while running against the no-op provider would be an excellent first step.

I will circle back to the flagd provider for python. I'm really only a python novice, but the flagd communication layer is all built automatically via .proto definitions, ideally, so I might be able to get it into a working order without much trouble.

I will circle back on that.
